# -*- coding: utf-8 -*-
"""World Happiness_Rui.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m9L4qB8cO6FQnd23Y6e1hHDda8YcUaqh
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

 

df2018=pd.read_csv('https://raw.githubusercontent.com/MauricioConceicao123/World-Happiness-Report---Webscraping/main/2018.csv')
df2018

df2018.sort_values('Social support', ascending=False, inplace=True)
socialsuport=df2018.head(10)

fig, ax=plt.subplots(figsize=(8,5))

ax=sns.barplot(socialsuport, x='Country or region', y='Social support', palette="ch:s=.25,rot=-.25")
ax.bar_label(ax.containers[0])
ax.set_xticklabels(socialsuport['Country or region'], rotation=45)

ax.set(title="Top 10 Country with the Best Social Support in 2018")
ax.set_xlabel('')
ax.set_ylabel('Rate Social Support')

df2018.sort_values('GDP per capita', ascending=False, inplace=True)
gdp2018=df2018.head(10)
gdp2018

fig, ax=plt.subplots(figsize=(8,5))

ax1=sns.barplot(gdp2018, x='Country or region', y='GDP per capita', palette="ch:s=.25,rot=-.25")
ax1.bar_label(ax.containers[0])
ax1.set_xticklabels(gdp2018['Country or region'], rotation=45)

ax1.set(title="Top 10 Country with the Best Values of GDP per Capita in 2018")
ax1.set_xlabel('')

"""#2019"""

df2019=pd.read_csv('https://raw.githubusercontent.com/MauricioConceicao123/World-Happiness-Report---Webscraping/main/2019.csv')
df2019

df2019.sort_values('Social support', ascending=False, inplace=True)
ss2019=df2019.head(10)

fig, ax=plt.subplots(figsize=(8,5))

ax=sns.barplot(ss2019, x='Country or region', y='Social support', palette="flare")
ax.bar_label(ax.containers[0])
ax.set_xticklabels(ss2019['Country or region'], rotation=45)

ax.set(title="Top 10 Country with the Best Social Support in 2019")
ax.set_xlabel('')
ax.set_ylabel('Rate Social Support')

df2019.sort_values('GDP per capita', ascending=False, inplace=True)
gdp2019=df2019.head(10)
gdp2019

fig, ax=plt.subplots(figsize=(8,5))

ax4=sns.barplot(gdp2019, x='Country or region', y='GDP per capita', palette="flare")
ax4.bar_label(ax.containers[0])
ax4.set_xticklabels(gdp2019['Country or region'], rotation=45)

ax4.set(title="Top 10 Country with the Best Values of GDP per Capita in 2019")
ax4.set_xlabel('')

from cycler import add
fig, ax=plt.subplots(2,2, figsize=(17,8))
plt.subplots_adjust(wspace=0.6, hspace=0.6)
row_headers = ["2018", "2019"]
col_headers = ["Top 10 Country with the Best Social Support", "Top 10 Country with the Best Values of GDP per Capita"]

ax1=sns.barplot(socialsuport, x='Country or region', y='Social support', palette="ch:s=.25,rot=-.25", ax=ax[0,0])
ax1.set_xticklabels(socialsuport['Country or region'], rotation=45, size=8)
ax1.set(title="Top 10 Country with the Best Social Support")
ax1.set_xlabel('')
#ax1.bar_label(ax.containers[0])

ax2=sns.barplot(ss2019, x='Country or region', y='Social support', palette="flare", ax=ax[1,0])
ax2.set_xticklabels(ss2019['Country or region'], rotation=45, size=8)

ax3=sns.barplot(gdp2018, x='Country or region', y='GDP per capita', palette="ch:s=.25,rot=-.25", ax=ax[0,1])
ax3.set_xticklabels(gdp2018['Country or region'], rotation=45, size=8)
ax3.set(title="Top 10 Country with the Best Values of GDP per Capita")
ax3.set_xlabel('')
#ax3.bar_label(ax.containers[0])

ax4=sns.barplot(gdp2019, x='Country or region', y='GDP per capita', palette="flare")
ax4.set_xticklabels(gdp2019['Country or region'], rotation=45, size=8)
#ax4.set(title="Top 10 Country with the Best Values of GDP per Capita in 2019")
ax4.set_xlabel('')
#ax4.bar_label(ax.containers[0])